id: P002901
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19156
  title: ངེད་ཕ་བུ་ཚོའི་མི་ཚེ།
  author: ''
  volumes:
    2d6d9c8634584afca437b1ca512da6f7:
      image_group_id: I8LS19158
      title: ''
      volume_number: 1
      total_pages: 335
      base_file: v001.txt
